spring:
  cloud:
    gateway:
      routes:
      - id: ms-users
        uri: lb://ms-users
        predicates:
          - Path=/ms-users/**
        filters:
          - StripPrefix=1
      - id: ms-accounts
        uri: lb://ms-accounts
        predicates:
          - Path=/ms-accounts/**
        filters:
          - StripPrefix=1