spring:
  cloud:
    gateway:
      routes:
      - id: ms-users
        uri: lb://ms-users
        predicates:
          - Path=/ms-users/**
        filters:
          - StripPrefix=1
      - id: ms-accounts
        uri: lb://ms-accounts
        predicates:
          - Path=/ms-accounts/**
        filters:
          - StripPrefix=1
      - id: ms-payments
        uri: lb://ms-payments
        predicates:
          - Path=/ms-payments/**
        filters:
          - StripPrefix=1
      - id: auth-server
        uri: lb://auth-server
        predicates:
          - Path=/auth-server/**
        filters:
          - StripPrefix=1